version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./config_local.py:/pgadmin4/config_local.py

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge